apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-ops-app
  namespace: demo
spec:
  project: default

  source:
    repoURL: https://github.com/si618/demo-ops-config.git
    targetRevision: HEAD
    path: main

  destination: 
    server: https://kubernetes.default.svc
    namespace: demo-ops-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true