apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-demo-app
  namespace: demo
spec:
  project: default

  source:
    repoURL: https://github.com/si618/ops-demo-config.git
    targetRevision: HEAD
    path: main

  destination: 
    server: https://kubernetes.default.svc
    namespace: ops-demo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true