apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atops-demo-application
  namespace: atops
spec:
  project: default

  source:
    repoURL: https://github.com/si618/atops-demo-config.git
    targetRevision: HEAD
    path: main

  destination: 
    server: https://kubernetes.default.svc
    namespace: atops-demo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true